version: "3"
services:
  masterNode:
    image: kadlab:latest # Make sure your Docker image has this name.
    container_name: master
    environment:
      - CONTAINER_NAME=master #Used by the go program to distinguish between master and other nodes
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1  
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    ports:
      - "8000:8050"
    networks:
      - kademlia_network
  kademliaNodes:
    image: kadlab:latest # Make sure your Docker image has this name.
    environment:
    - CONTAINER_NAME=other
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 49  
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    ports:
      - "8001-8049:8050"
    depends_on:
      - masterNode
    networks:
      - kademlia_network
      
networks:
  kademlia_network: